export default {
    SET_ANSWERS: 'SET_ANSWERS',
    SET_CURRENT_TEST: 'SET_CURRENT_TEST',
    START_TEST: 'START_TEST',
    COMPLETE_TEST: 'COMPLETE_TEST',
    CLOSE_TEST: 'CLOSE_TEST',
    CLEAR_TOPIC: 'CLEAR_TOPIC',
}
